version: '3'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - NODE_ENV=production
      # Configurações de banco de dados (usando SQLite por padrão)
      # Para usar PostgreSQL, descomente as linhas abaixo e ajuste as configurações
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n
      
      # Configurações de e-mail (opcional)
      # - N8N_EMAIL_MODE=smtp
      # - N8N_SMTP_HOST=smtp.gmail.com
      # - N8N_SMTP_PORT=465
      # - N8N_SMTP_USER=user@gmail.com
      # - N8N_SMTP_PASS=password
      # - N8N_SMTP_SENDER=n8n@localhost
      
      # Configurações de timezone
      - GENERIC_TIMEZONE=America/Sao_Paulo
      
      # Configurações de segurança
      - N8N_BASIC_AUTH_ACTIVE=false
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=admin
      
      # Habilitar execuções webhook
      - N8N_ENABLE_WEBHOOK_ENDPOINT=true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network

  # Configuração do PostgreSQL (opcional - descomente para usar)
  # postgres:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=n8n
  #     - POSTGRES_PASSWORD=n8n
  #     - POSTGRES_DB=n8n
  #     - POSTGRES_NON_ROOT_USER=n8n
  #     - POSTGRES_NON_ROOT_PASSWORD=n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n-network

volumes:
  n8n_data:
  # postgres_data:

networks:
  n8n-network:
    driver: bridge